[package]
name = "test_rust"
version = "0.1.0"
edition = "2021"


[dependencies]
rusqlite = { version = "0.31.0", features = ["bundled"] }
ctrlc = "3.1"

[lib]
name = "test_rust"
path = "src/my_lib.rs"
